plugin:
    name: 'pensoft.externaldocuments::lang.plugin.name'
    description: 'pensoft.externaldocuments::lang.plugin.description'
    author: Pensoft
    icon: oc-icon-file-o
    homepage: ''
navigation:
    main-menu-item:
        label: 'Public documents'
        url: pensoft/externaldocuments/folders
        icon: icon-file
        sideMenu:
            side-menu-item:
                label: Folders
                url: pensoft/externaldocuments/folders
                icon: icon-folder
            side-menu-item2:
                label: Types
                url: pensoft/externaldocuments/types
                icon: icon-star-half-empty
