name: Types
form: $/pensoft/externaldocuments/models/types/fields.yaml
modelClass: Pensoft\ExternalDocuments\Models\Types
defaultRedirect: pensoft/externaldocuments/types
create:
    redirect: 'pensoft/externaldocuments/types/update/:id'
    redirectClose: pensoft/externaldocuments/types
update:
    redirect: pensoft/externaldocuments/types
    redirectClose: pensoft/externaldocuments/types
