list: $/pensoft/externaldocuments/models/folders/columns.yaml
modelClass: Pensoft\ExternalDocuments\Models\Folders
title: Folders
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
showTree: 1 //Display tree view
treeExpanded: 1 // Tree expanded by default
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/externaldocuments/folders/update/:id'
